<a href="https://colab.research.google.com/github/Aqibkhan037/Artificial-intelligence/blob/main/Muhammad%20Aqib..LabQuiz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('/content/reviews_dataset.csv')

In [5]:
df.head()

news      type
0  China had role in Yukos split-up\n \n China le...  business
1  Oil rebounds from weather effect\n \n Oil pric...  business
2  Indonesia 'declines debt freeze'\n \n Indonesi...  business
3  $1m payoff for former Shell boss\n \n Shell is...  business
4  US bank in $515m SEC settlement\n \n Five Bank...  business

In [6]:
import pandas as pd
import string


import re
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer


nltk.download('wordnet')
nltk.download('stopwords')
nltk.download('punkt_tab')


stopwords.words('english')
exclude = string.punctuation

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


In [7]:
def remove_html_tags(text):
    pattern = re.compile('<.*?>')
    return pattern.sub(r'', text)

def remove_url(text):
    pattern = re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub(r'', text)

#exclude = "!.,?"
def remove_punc(text):
    return text.translate(str.maketrans('', '', exclude))

In [8]:



df['news'] = df['news'].str.lower()

df['news'] = df['news'].apply(remove_html_tags)

df['news'] = df['news'].apply(remove_url)

df['news'] = df['news'].apply(remove_punc)

#df['review'] = df['review'].apply(word_tokenize)

#df['review'] = df['review'].apply(remove_stopwords)

#df['review'] = df['review'].apply(lemmatize_words)

In [9]:
df.head()

news      type
0  china had role in yukos splitup\n \n china len...  business
1  oil rebounds from weather effect\n \n oil pric...  business
2  indonesia declines debt freeze\n \n indonesia ...  business
3  1m payoff for former shell boss\n \n shell is ...  business
4  us bank in 515m sec settlement\n \n five bank ...  business

In [10]:
from sklearn.preprocessing import LabelEncoder

#X = df.drop('sentiment', axis=1)
X = df['news']
Y = df['type']

print(X)
print(Y)

encoder = LabelEncoder()
Y = encoder.fit_transform(Y)

print(Y)

0       china had role in yukos splitup\n \n china len...
1       oil rebounds from weather effect\n \n oil pric...
2       indonesia declines debt freeze\n \n indonesia ...
3       1m payoff for former shell boss\n \n shell is ...
4       us bank in 515m sec settlement\n \n five bank ...
                              ...                        
2220    microsoft launches its own search\n \n microso...
2221    warnings about junk mail deluge\n \n the amoun...
2222    microsoft gets the blogging bug\n \n software ...
2223    gamers snap up new sony psp\n \n gamers have b...
2224    apple laptop is greatest gadget\n \n the apple...
Name: news, Length: 2225, dtype: object
0       business
1       business
2       business
3       business
4       business
          ...   
2220        tech
2221        tech
2222        tech
2223        tech
2224        tech
Name: type, Length: 2225, dtype: object
[0 0 0 ... 4 4 4]


In [11]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix

X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

print(X_train.shape)
#print(X_train.head)

#print(X_train)
#print(X_test)

# Initialize the CountVectorizer
vectorizer = CountVectorizer()

# Fit the vectorizer on the training data and transform it
X_train_bow = vectorizer.fit_transform(X_train)

# Transform the test data using the same vectorizer
X_test_bow = vectorizer.transform(X_test)

# Output the shapes of the resulting Bag of Words matrices
print(f"Shape of X_train_bow: {X_train_bow.shape}")
print(f"Shape of X_test_bow: {X_test_bow.shape}")

# Applying Random Forest Classifier
rf = RandomForestClassifier()

rf.fit(X_train_bow,y_train)
y_pred = rf.predict(X_test_bow)
#accuracy_score(y_test,y_pred)

print (accuracy_score(y_test,y_pred))
print (confusion_matrix(y_test,y_pred))

(1780,)
Shape of X_train_bow: (1780, 30962)
Shape of X_test_bow: (445, 30962)
0.946067415730337
[[110   0   3   0   2]
 [  2  66   0   2   2]
 [  4   0  71   1   0]
 [  0   0   0 102   0]
 [  4   2   0   2  72]]


In [12]:
cv = CountVectorizer(ngram_range=(2,2))

X_train_n_gram = cv.fit_transform(X_train)
X_test_n_gram = cv.transform(X_test)

# Output the shapes of the resulting Bag of Words matrices
print(f"Shape of X_train_bow: {X_train_n_gram.shape}")
print(f"Shape of X_test_bow: {X_test_n_gram.shape}")

rf = RandomForestClassifier()

rf.fit(X_train_n_gram,y_train)
y_pred = rf.predict(X_test_n_gram)

print (accuracy_score(y_test,y_pred))
print (confusion_matrix(y_test,y_pred))

Shape of X_train_bow: (1780, 285808)
Shape of X_test_bow: (445, 285808)
0.8674157303370786
[[106   1   2   5   1]
 [  5  49   0  17   1]
 [  3   0  65   8   0]
 [  0   0   0 102   0]
 [ 12   1   0   3  64]]


In [13]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix




In [14]:

from nltk.corpus import stopwords
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [15]:
def remove_stopwords(text):
    new_text = []

    for word in text.split():
        if word in stopwords.words('english'):
            new_text.append('')
        else:
            new_text.append(word)
    x = new_text[:]
    new_text.clear()
    return " ".join(x)

In [16]:
df['news'] = df['news'].apply(remove_stopwords)

In [17]:
df.head()

news      type
0  china  role  yukos splitup china lent russia 6...  business
1  oil rebounds  weather effect oil prices recove...  business
2  indonesia declines debt freeze indonesia  long...  business
3  1m payoff  former shell boss shell   pay 1m â£...  business
4  us bank  515m sec settlement five bank  americ...  business

In [18]:
import nltk
nltk.download('punkt_tab')
from nltk.tokenize import word_tokenize,sent_tokenize


[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


In [19]:
df['news'] = df['news'].apply(word_tokenize)

In [20]:
df.head()

news      type
0  [china, role, yukos, splitup, china, lent, rus...  business
1  [oil, rebounds, weather, effect, oil, prices, ...  business
2  [indonesia, declines, debt, freeze, indonesia,...  business
3  , payoff, former, shell, boss, shell, pay, ...  business
4  [us, bank, 515m, sec, settlement, five, bank, ...  business

In [21]:
# Use trigram instead of bigram
cv = CountVectorizer(ngram_range=(3, 3))

# Fit and transform the training data and transform the test data
X_train_n_gram = cv.fit_transform(X_train)
X_test_n_gram = cv.transform(X_test)

# Output the shapes of the resulting Bag of Words matrices
print(f"Shape of X_train_bow: {X_train_n_gram.shape}")
print(f"Shape of X_test_bow: {X_test_n_gram.shape}")

# Train a Random Forest Classifier
rf = RandomForestClassifier()
rf.fit(X_train_n_gram, y_train)

# Predict on the test data
y_pred = rf.predict(X_test_n_gram)

# Print the accuracy and confusion matrix
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Shape of X_train_bow: (1780, 508062)
Shape of X_test_bow: (445, 508062)
0.7370786516853932
[[ 82   0   4  28   1]
 [  6  35   0  30   1]
 [  3   0  56  15   2]
 [  0   0   0 102   0]
 [  9   2   0  16  53]]


In [22]:
import nltk
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer
lemmitizer = WordNetLemmatizer()
def lemmitize_words(text):
    return " ".join([lemmitizer.lemmatize(word,pos='v') for word in text.split()])

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [23]:
def lemmatize_words(tokens):
    return [lemmitizer.lemmatize(word,pos='v') for word in tokens]
    #return " ".join([lemmatizer.lemmatize(word) for word in tokens])

# Lemmatizing the tokenized words in the 'review' column
df['lemmatized_news'] = df['news'].apply(lemmatize_words)

In [24]:
df.head()

news      type  \
0  [china, role, yukos, splitup, china, lent, rus...  business   
1  [oil, rebounds, weather, effect, oil, prices, ...  business   
2  [indonesia, declines, debt, freeze, indonesia,...  business   
3  , payoff, former, shell, boss, shell, pay, ...  business   
4  [us, bank, 515m, sec, settlement, five, bank, ...  business   

                                     lemmatized_news  
0  [china, role, yukos, splitup, china, lend, rus...  
1  [oil, rebound, weather, effect, oil, price, re...  
2  [indonesia, decline, debt, freeze, indonesia, ...  
3  , payoff, former, shell, boss, shell, pay, ...  
4  [us, bank, 515m, sec, settlement, five, bank, ...

In [25]:
df.drop('news',axis=1,inplace=True)

In [27]:
from sklearn.preprocessing import LabelEncoder

#X = df.drop('sentiment', axis=1)
X = df['lemmatized_news']
Y = df['type']

print(X)
print(Y)

encoder = LabelEncoder()
Y = encoder.fit_transform(Y)

print(Y)

0       [china, role, yukos, splitup, china, lend, rus...
1       [oil, rebound, weather, effect, oil, price, re...
2       [indonesia, decline, debt, freeze, indonesia, ...
3       , payoff, former, shell, boss, shell, pay, ...
4       [us, bank, 515m, sec, settlement, five, bank, ...
                              ...                        
2220    [microsoft, launch, search, microsoft, unveil,...
2221    [warnings, junk, mail, deluge, amount, spam, c...
2222    [microsoft, get, blogging, bug, software, gian...
2223    [gamers, snap, new, sony, psp, gamers, buy, al...
2224    [apple, laptop, greatest, gadget, apple, power...
Name: lemmatized_news, Length: 2225, dtype: object
0       business
1       business
2       business
3       business
4       business
          ...   
2220        tech
2221        tech
2222        tech
2223        tech
2224        tech
Name: type, Length: 2225, dtype: object
[0 0 0 ... 4 4 4]


In [28]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix

X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

print(X_train.shape)
#print(X_train.head)

#print(X_train)
#print(X_test)

# Initialize the CountVectorizer
vectorizer = CountVectorizer()

# Fit the vectorizer on the training data and transform it
X_train_bow = vectorizer.fit_transform(X_train)

# Transform the test data using the same vectorizer
X_test_bow = vectorizer.transform(X_test)

# Output the shapes of the resulting Bag of Words matrices
print(f"Shape of X_train_bow: {X_train_bow.shape}")
print(f"Shape of X_test_bow: {X_test_bow.shape}")

# Applying Random Forest Classifier
rf = RandomForestClassifier()

rf.fit(X_train_bow,y_train)
y_pred = rf.predict(X_test_bow)
#accuracy_score(y_test,y_pred)

print (accuracy_score(y_test,y_pred))
print (confusion_matrix(y_test,y_pred))

(1780,)


AttributeError: 'list' object has no attribute 'lower'

In [30]:

X = [str(x) for x in X]

# Splitting the data
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# Initialize the CountVectorizer
vectorizer = CountVectorizer()

# Fit the vectorizer on the training data and transform it
X_train_bow = vectorizer.fit_transform(X_train)

# Transform the test data using the same vectorizer
X_test_bow = vectorizer.transform(X_test)

# Output the shapes of the resulting Bag of Words matrices
print(f"Shape of X_train_bow: {X_train_bow.shape}")
print(f"Shape of X_test_bow: {X_test_bow.shape}")

# Applying Random Forest Classifier
rf = RandomForestClassifier(n_estimators=150)

rf.fit(X_train_bow, y_train)
y_pred = rf.predict(X_test_bow)

# Evaluate the model
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))


Shape of X_train_bow: (1780, 26137)
Shape of X_test_bow: (445, 26137)
0.9393258426966292
[[109   0   6   0   0]
 [  5  64   1   1   1]
 [  2   0  72   1   1]
 [  0   0   0 102   0]
 [  4   2   1   2  71]]


In [31]:

X = [str(x) for x in X]

# Splitting the data
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# Initialize the CountVectorizer
vectorizer = CountVectorizer()

# Fit the vectorizer on the training data and transform it
X_train_bow = vectorizer.fit_transform(X_train)

# Transform the test data using the same vectorizer
X_test_bow = vectorizer.transform(X_test)

# Output the shapes of the resulting Bag of Words matrices
print(f"Shape of X_train_bow: {X_train_bow.shape}")
print(f"Shape of X_test_bow: {X_test_bow.shape}")

# Applying Random Forest Classifier
rf = RandomForestClassifier(n_estimators=150)

rf.fit(X_train_bow, y_train)
y_pred = rf.predict(X_test_bow)

# Evaluate the model
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))


Shape of X_train_bow: (1780, 26137)
Shape of X_test_bow: (445, 26137)
0.9415730337078652
[[110   0   3   1   1]
 [  3  65   0   3   1]
 [  3   0  72   1   0]
 [  0   0   0 102   0]
 [  4   2   1   3  70]]


In [32]:

X = [str(x) for x in X]

# Splitting the data
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# Initialize the CountVectorizer
vectorizer = CountVectorizer()

# Fit the vectorizer on the training data and transform it
X_train_bow = vectorizer.fit_transform(X_train)

# Transform the test data using the same vectorizer
X_test_bow = vectorizer.transform(X_test)

# Output the shapes of the resulting Bag of Words matrices
print(f"Shape of X_train_bow: {X_train_bow.shape}")
print(f"Shape of X_test_bow: {X_test_bow.shape}")

# Applying Random Forest Classifier
rf = RandomForestClassifier(n_estimators=200)

rf.fit(X_train_bow, y_train)
y_pred = rf.predict(X_test_bow)

# Evaluate the model
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))


Shape of X_train_bow: (1780, 26137)
Shape of X_test_bow: (445, 26137)
0.9550561797752809
[[110   0   3   1   1]
 [  4  66   1   0   1]
 [  1   0  74   1   0]
 [  0   0   0 102   0]
 [  3   1   1   2  73]]


Shape of X_train_bow: (1780, 26137)
Shape of X_test_bow: (445, 26137)
0.9483146067415731
[[109   0   5   0   1]
 [  2  66   2   1   1]
 [  2   0  74   0   0]
 [  0   0   0 102   0]
 [  3   2   1   3  71]]


**Here is the my Lab quiz, I performed the task in the following steps.**
**Step 1:** I download the dataset, read it as a dataFrame.
**Step 2:** Removed url, punctuation, and html links.
**Step 3:** After that I trained my Random forest model on this dataset, and I got an accuracy of 94....
On bigram I got accuracy of 86...
**Step 4:** After that I removed the stopwords and tokanized the df and trained my Random forest model and bag of word as trigram and got accuracy of 73
**Step 5:** After that I lemmatized the news and then trianed my Random forest model with the Number of trees set to 150 and got accuracy of 94
**Step 6:** I increased the number of trees to 200 and then got accuracy of 95